# Generated by Django 4.2.15 on 2024-08-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='user_name')),
                ('category1', models.CharField(blank=True, max_length=20, null=True, verbose_name='カテゴリー1')),
                ('category2', models.CharField(blank=True, max_length=20, null=True, verbose_name='カテゴリー2')),
                ('product_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='製品名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('durability', models.IntegerField(blank=True, null=True, verbose_name='耐久性')),
                ('portability', models.IntegerField(blank=True, null=True, verbose_name='携帯性')),
                ('functionality', models.IntegerField(blank=True, null=True, verbose_name='機能性')),
                ('repeat', models.IntegerField(blank=True, null=True, verbose_name='リピート')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品紹介')),
                ('registration_time', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'rank_t_rankdata',
            },
        ),
    ]
