# Generated by Django 4.2.15 on 2024-08-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankdata',
            name='maker',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='メーカー'),
        ),
    ]
