# Generated by Django 4.2.15 on 2024-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_rankdata_maker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(blank=True, max_length=20, null=True, verbose_name='カテゴリー1')),
                ('registration_time', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'rank_m_category1',
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(blank=True, max_length=20, null=True, verbose_name='カテゴリー1')),
                ('category2', models.CharField(blank=True, max_length=20, null=True, verbose_name='カテゴリー2')),
                ('registration_time', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'rank_m_category2',
            },
        ),
        migrations.AlterField(
            model_name='rankdata',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品紹介'),
        ),
    ]
