# Generated by Django 4.2.15 on 2024-08-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_category1_category2_alter_rankdata_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankdata',
            unique_together={('user_name', 'category1', 'category2')},
        ),
    ]
